_core:
  default_config_hash: o7UdhCuEHWPn7Pz1c9KT7W818Cvg9EMVd2Gay1qKKPk
features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: ''
favicon:
  use_default: 0
  path: ''
